spring.application.name=music-sharing-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.sql.init.mode=always
spring.datasource.username=postgres
spring.datasource.password=password

logging.level.org.springframework.jdbc=DEBUG

content.properties.welcomeMessage=Welcome to Nicks Content Calendar
content.properties.about=This is Nicks content calendar

spring.profiles.active=dev

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always